### ISSUE TITLE
Command line not working on Windows

### ISSUE THREAD

**Issue by Ashargin** [mjothy/grid2viz#15] opened 2020-05-20 14:51 UTC
Hello,

When installing the repository on a Windows system and using the command line `grid2viz`, I get:
```
C:\Users\Loïc>grid2viz
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\grid2viz.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'grid2viz'
```

However, this still works when executing from the repository directory.
There may be an issue with Windows here.

**Comment by vinault** [comment] 2020-06-17 08:35
Hi @Ashargin,

I'm sorry but I cannot reproduce this error. Can give me some detail on the corresponding installation process ? Thank you.

**Comment by Ashargin** [comment] 2020-06-18 06:25
Hello,

The installation was done as suggested in the readme file :
```
git clone https://github.com/mjothy/Grid2Viz.git
cd Grid2Viz
pip install -U .
```

**Comment by marota** [comment] 2020-06-22 12:15
@Ashargin could youy try again by making a virtual environment to be sure to have the same package versions for everything?

**Comment by marota** [comment] 2020-10-05 12:33
Ok now after reply of @Ashargin. Closing

**Closed** 2020-10-05 12:34 UTC
